package rs.medico;


import model.MedicoPediatra;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ruan Nunes
 * @date   03/06/2020
 */
public class TelaPrincipal extends javax.swing.JFrame {

    static int qtdMedicos = 0;
    static MedicoPediatra vetor[] = new MedicoPediatra[10];
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new JDesktopPane();
        jMenuBar1 = new JMenuBar();
        jMenuCadastros = new JMenu();
        jMenuItemCadastrosMedicos = new JMenuItem();
        jMenuListagens = new JMenu();
        jMenuItemListagensMedicos = new JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas de Medicos");

        jMenuCadastros.setText("Cadastros");
        jMenuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosActionPerformed(evt);
            }
        });

        jMenuItemCadastrosMedicos.setText("Medico");
        jMenuItemCadastrosMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrosMedicosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastrosMedicos);

        jMenuBar1.add(jMenuCadastros);

        jMenuListagens.setText("Listagens");
        jMenuListagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListagensActionPerformed(evt);
            }
        });

        jMenuItemListagensMedicos.setText("Medicos");
        jMenuItemListagensMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListagensMedicosActionPerformed(evt);
            }
        });
        jMenuListagens.add(jMenuItemListagensMedicos);

        jMenuBar1.add(jMenuListagens);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1245, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrosMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrosMedicosActionPerformed
        TelaCadastroMedico objTelaMedico = new TelaCadastroMedico();
        this.jDesktopPane1.add(objTelaMedico);
        objTelaMedico.show();
    }//GEN-LAST:event_jMenuItemCadastrosMedicosActionPerformed

    private void jMenuItemListagensMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListagensMedicosActionPerformed
        TelaListagemMedicos objTelaListagemMedicos = new TelaListagemMedicos();
        this.jDesktopPane1.add(objTelaListagemMedicos);
        objTelaListagemMedicos.show();
    }//GEN-LAST:event_jMenuItemListagensMedicosActionPerformed

    private void jMenuListagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListagensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuListagensActionPerformed

    private void jMenuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItemCadastrosMedicos;
    private javax.swing.JMenuItem jMenuItemListagensMedicos;
    private javax.swing.JMenu jMenuListagens;
    // End of variables declaration//GEN-END:variables
}
